version: '3'

services:
  app:
    image: 'werewolves:latest'
    build:
      context: .
    container_name: werewolves
    depends_on:
      - db
    environment:
      - POSTGRESQL_HOSTNAME=db
      - POSTGRESQL_USERNAME=werewolves
      - POSTGRESQL_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
    - 8080:8080

  db:
    image: 'postgres:13-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=werewolves
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=werewolves
    ports:
    - 5432:5432